baseURL = "http://vvuri.github.io/"
languageCode = "ru"

contentdir = "content"
publishdir = "public"
builddrafts = false
baseUrl = ""
canonifyurls = true
title = "All blogs"
theme = "bootstrap-bp-hugo-theme"
startPageColumns = true
disqusShortname = "vvuri"
copyright = "Yuri Vinogradov"

[indexes]
  category = "categories"
  tag = "tags"

[params]
  search_engine = false
  twitter_username = "vvuri"
  paginate = true
  description = "Education Python, Golang, Machine Learning and Robotics. Work in QA."
  #images = ["logo.jpg"]
  showPostSummary = true
  startPageColumns = true

[author]
  name = "vvuri"
  
[sitemap]
    changefreq = "weekly"
    priority = 0.5

[permalinks]
    posts = "/:year/:month/:slug/"
    post = "/:year/:month/:slug/"
    pages = "/:slug/"
    page = "/:slug/"